# Generated by Django 4.1.3 on 2022-12-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='time',
            field=models.DateTimeField(verbose_name='案發日期'),
        ),
    ]
