# Generated by Django 4.1.3 on 2022-12-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0002_alter_emergency_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=50)),
                ('member', models.CharField(max_length=10)),
                ('time', models.DateTimeField(verbose_name='紀錄時間')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('time', models.DateTimeField(verbose_name='建立時間')),
            ],
        ),
    ]
