# Generated by Django 4.1.3 on 2022-12-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0003_logrecord_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='account',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='紀錄時間'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
    ]
