# Generated by Django 4.1.4 on 2023-01-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0004_rename_account_member_username_alter_logrecord_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
