# Generated by Django 4.1.4 on 2023-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0005_alter_emergency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
