# Generated by Django 4.1.4 on 2023-01-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0006_alter_emergency_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emergency',
            table='EMERGENCY',
        ),
    ]
