# Generated by Django 4.1.4 on 2023-01-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0007_alter_emergency_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emergency',
            table=None,
        ),
    ]
