# Generated by Django 4.1.4 on 2023-02-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0008_alter_emergency_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
