# Generated by Django 4.1.4 on 2023-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0012_alter_emergency_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='car',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
